### ISSUE TITLE
Error in CP

### ISSUE THREAD

**Issue by rebornmedia1** [Stillat/statamic-search-report#1]
I am getting the following error when trying to access the results in utilities.  I am using Statamic 4.57.2. Any ideas what could be causing this?

local.ERROR: Declaration of Stillat\StatamicSearchReport\Http\Resources\SearchLogResource::toArray(Illuminate\Http\Request $request): array must be compatible with Illuminate\Http\Resources\Json\ResourceCollection::toArray($request) {"userId":"47f0e4e9-5b7d-463b-9d1f-b1f117d0a00e","exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Declaration of Stillat\\StatamicSearchReport\\Http\\Resources\\SearchLogResource::toArray(Illuminate\\Http\\Request $request): array must be compatible with Illuminate\\Http\\Resources\\Json\\ResourceCollection::toArray($request) at /Users/myname/Documents/mysite/vendor/stillat/statamic-search-report/src/Http/Resources/SearchLogResource.php:16)

**Comment by JohnathonKoster** [comment]
Hey, there! Updating to 1.1.1 should clear that up for you 👍
